version: "3.2"
services:
  flask:
    build: ./app
    image: flask:latest
    container_name: pythonbp25
    restart: always
    environment:
      - APP_NAME=flask
    expose:
      - 8080
    stdin_open: true
    tty: true
    volumes:
     - ./app:/home/myuser
  nginx:
    image: nginx:latest
    build: ./nginx
    container_name: nginxbp25
    restart: always
    ports:
     - "80:80"
